### ISSUE TITLE
[fpu] precision problem in `int` and `floor` functions

### ISSUE THREAD

**Issue by Mo-Gul** [pgf-tikz/pgf#734] opened 2019-08-27 07:08 UTC
I am pretty sure that I encountered that specific problem several times now, so maybe it can be fixed. When `fpu` is enabled the `floor` and `int` functions can yield wrong results as e.g. shown in the following MWE.

Here a list were I know that this problem encountered:
- https://tex.stackexchange.com/q/505871/95441
- https://tex.stackexchange.com/a/249507/95441

--- 

    \documentclass[border=5pt,varwidth]{standalone}
    \usepackage{tikz}
        \usetikzlibrary{fpu}
    \begin{document}
        \textbf{Without \texttt{fpu}:} \\
        \pgfmathparse{floor(12/4)}\pgfmathresult{} instead of 3 \\
        \pgfmathparse{int(12/4)}\pgfmathresult{} instead of 3 \\

        \textbf{With \texttt{fpu}:} \\
        \pgfkeys{
            /pgf/fpu,
            /pgf/fpu/output format=fixed,
        }
        \pgfmathparse{floor(12/4)}\pgfmathresult{} instead of 3 \\
        \pgfmathparse{int(12/4)}\pgfmathresult{} instead of 3 \\
    \end{document}

![image](https://user-images.githubusercontent.com/17992976/63748685-18591e80-c8aa-11e9-8716-2e9ba8ef5ec2.png)

**Comment by hmenke** [comment] 2019-11-04 05:28
The problem is neither `floor`, nor `int`, but the fact that
```latex
\pgfkeys{/pgf/fpu}\pgfmathparse{12/4}\pgfmathresult
```
outputs `1Y2.9999e0]`.

**Comment by hmenke** [comment] 2019-11-04 05:49
The two input arguments to `\pgfmathfloatdivide@` are getting rescaled here:
https://github.com/pgf-tikz/pgf/blob/08275e3034d5f64fa43ff1e0af0991911f1fb21a/tex/generic/pgf/libraries/pgflibraryfpu.code.tex#L1297-L1303
After that we have `\pgfmathfloat@arga=12.000` and `\pgfmathfloat@argb=40.00`.  Most of the rest of the function does nothing because neither number is negative, or zero, or nan, or inf.  Thus we fall through to the division of the mantissae.
https://github.com/pgf-tikz/pgf/blob/08275e3034d5f64fa43ff1e0af0991911f1fb21a/tex/generic/pgf/libraries/pgflibraryfpu.code.tex#L1385
So we essentially do
```latex
\dimen0=12pt
\divide\dimen0 by 40
```
and that is by TeX's arithmetic `0.29999pt`.  So I conclude that there is not really anything I can do here.

When you encounter precision problems you could instead use `l3fp` which has full IEEE754 precision.

**Comment by hmenke** [comment] 2019-11-27 21:46
@Mo-Gul I'm about to close this as wont-fix because I can't actually do anything about it.  Are you okay with that?

**Comment by Mo-Gul** [comment] 2019-11-30 12:14
If there *really* isn't anything that you can do I/we'll have to live with it and it is fine to close it.

So please allow me to ask for one maybe possible solution/workaround:
Would it be possible to implement a special handler that checks for the result of `0.29999pt` and than change that to `0.3pt`?

**Comment by hmenke** [comment] 2019-12-06 00:52
You mean in each and every of the thousands of invocations of `\pgfmathfloatdivide@` check if the operands are 12 and 40 and then return 0.3?  That sounds horribly inefficient.

**Comment by Mo-Gul** [comment] 2019-12-06 05:13
Is it a *guess* or a *statement* that "this" is "horribly inefficient"?
I guess there isn't a performance test yet, right? So if you would provide a patch (here or via email) I would be happy to test compilation times for the `codeexample`s with and without the patch using the [parallel build script](https://github.com/pgf-tikz/pgf/issues/640#issuecomment-511116534).

Just to be sure: One really would need to check for `12` and `40` and cannot directly hard-code the result `0.29999pt`? If yes, would it be an option to just do the calculation *once* and store the result which is then used?

**Comment by hmenke** [comment] 2019-12-06 08:41
Well yes, of course there would have to be a check for the operand being 12 and 40 because not every division amounts to 0.3, right?  Since it is an extra branch with two comparisons it will necessarily be slower than anything without this branch.  Also I presume that 12 and 40 will not be the only exceptions, so we'd end up with a huge table of exceptions, massively slowing down the code.

**Comment by josephwright** [comment] 2019-12-06 08:45
I'm with @hmenke here: if you _need_ a real FPU, use the LaTeX3 one, as it's designed from the ground up to handle this sort of thing (at the cost that it is slower than the `pgf` one).

**Comment by Mo-Gul** [comment] 2019-12-07 20:53
You are the experts, so I trust your opinion. So you are welcome to close this issue.

But could you state an example here (or at one of the TeX.SX questions) on how to *use* the `l3fp` package to solve/circumvent this issue!? Many thanks in advance!

**Closed as completed** 2019-12-10 03:02 UTC
Labels: closed-wont-fix, pgfmath, fpu

**Comment by muzimuzhi** [comment] 2021-09-25 14:07
> So we essentially do
> ```
> \dimen0=12pt
> \divide\dimen0 by 40
> ```
> 
> and that is by TeX's arithmetic `0.29999pt`. So I conclude that there is not really anything I can do here.

Using eTeX's expression may help here since
> the results of divisions and scalings are rounded, whereas TeX’s `\divide` truncates.

according to `texdoc etex`, sec. 3.5 "Expressions". For example `\dimen0=\dimexpr12pt/40\relax` will assign `\dimen0` `0.3pt`.

PS: I (re)read this issue when searched for possible duplicates of [TeX-SX question no.611573](https://tex.stackexchange.com/q/611573), in which one of the causes is about the jumping result of `divide`.

**Comment by hmenke** [comment] 2021-09-25 17:25
@muzimuzhi https://github.com/hmenke/pgf/commit/50778951982497e0999aae8aff419cccc75fd334

Doesn't pass CI unfortunately.
