### ISSUE TITLE
Position of text in rotated nodes changed with xelatex

### ISSUE THREAD

**Issue by samcarter** [pgf-tikz/pgf#709] opened 2019-07-15 09:56 UTC
Consider the following MWE to be compiled with xelatex

```
% !TeX TS-program = xelatex
\documentclass{article}

\usepackage{tikz}

\begin{document}

  \begin{tikzpicture}
  \fill[black, rotate=-20] (0.45,1.75) rectangle (1.25,2.35);
   \node[rotate=-20, color=gray] at (1.5,1.65) {1};
  \end{tikzpicture}
  
\end{document}
```

Prior to commit https://github.com/pgf-tikz/pgf/commit/d0f66607f379dadd6d5a435fa86567fe36cfb842 the result would be:

![Screen Shot 2019-07-15 at 11 52 30](https://user-images.githubusercontent.com/43832342/61208271-4b2ec500-a6f7-11e9-8bc4-77c13c63247e.png)

After this commit the text is no longer inside the node:

![Screen Shot 2019-07-15 at 11 52 46](https://user-images.githubusercontent.com/43832342/61208361-892be900-a6f7-11e9-9c70-0ea20dd46b1b.png)

Is this change intentional? 

(pdflatex and lualatex seems not to be affected)

**Comment by hmenke** [comment] 2019-07-15 10:02
Duplicate of https://github.com/pgf-tikz/pgf/issues/708
Please search existing issues first before opening a new one.

**Closed as completed by hmenke** 2019-07-15 10:02 UTC
Labels: closed-duplicate

**Comment by samcarter** [comment] 2019-07-15 11:34
@hmenke Sorry for the duplicate! I saw the other issue before posting, it just seemed to be specific to scaled graphics, so I did not make the connection that this is the same issue for text in nodes.
