### ISSUE TITLE
doc example rendered wrong: Part IX: The Basic Layer

### ISSUE THREAD

**Issue by nsajko** [pgf-tikz/pgf#1241] opened 2023-02-13 13:40 UTC
### Version

3.1.10

### Details

The example in the PDF, under the "Part IX": "The Basic Layer" title, is obviously wrong in both Firefox and Chromium.

Chromium:

![chromium](https://user-images.githubusercontent.com/4944410/218473123-4e8af464-401c-421a-822d-3dadb4623bad.png)

Firefox:

![firefox](https://user-images.githubusercontent.com/4944410/218473190-c21eec8a-7077-4756-b41c-f0c75780048a.png)

I'm a total newbie so I'll leave it to others to figure out what happened.

**Comment by muzimuzhi** [comment] 2023-02-14 03:21
Thanks for reporting. The underlying cause is shared with #1238, hence should be fixed by #1239.

To check the problem will indeed be resolved, you can down the artifact of latest manual workflow run for #1239 here: https://github.com/pgf-tikz/pgf/actions/runs/4160066552 (click the artifact named "pgfmanual" near the end of the page.)

**Comment by muzimuzhi** [comment] 2023-02-14 04:53
To make similar things in one place, explanation to the case your reported (and similar ones) is added in https://github.com/pgf-tikz/pgf/issues/1238#issuecomment-1429108528, and I'll mark current issue as duplicate of #1238 hence close it.

Duplicate of #1238 

(hmm the condition to trigger GitHub's "[Marking issues as a duplicate](https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate)" is strict)

**Comment by muzimuzhi** [comment] 2023-02-14 04:56
Duplicate of #1238

**Closed as not planned** 2023-10-24 19:02 UTC
Labels: manual
