### ISSUE TITLE
"node contents" is no more available in label

### ISSUE THREAD

**Issue by kpym** [pgf-tikz/pgf#645] opened 2019-04-04 10:22 UTC
Normally a label is a node and we can use it as such, at least this was the case before version 3.1 of TikZ.

Now when I try to use `node contents` in `label`, for example like this : 

```latex
\documentclass[tikz,border=7pt]{standalone}
\begin{document}
  \tikz\node[label={[node contents=B]}]{A};
\end{document}
```
I receive the following error 

```
! Package tikz Error: Giving up on this path. Did you forget a semicolon?.
```

This is the same error that we obtain if we use `node contents` style within node containing `{}`, like this `\node[node contents=B]{};`.

I don't know if this is a bug or for some good reasons the new implémentation of `label` use `{}` in place of `node contents`.

Before to submit this issue I asked [a question](https://tex.stackexchange.com/q/477295) on TeX.SW but nowbody there was able to clarify the situation.

**Note :** I'm happy to see that you have moved to GitHub ! :tada:

**Comment by hmenke** [comment] 2019-04-05 01:47
Confirmed.  In TeX Live 2017 it still worked.

Although this one still works for me with the current master.
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
  \node[node contents=B]{};
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment] 2019-04-05 02:27
Fixed in https://github.com/hmenke/pgf/commit/c69793450d9318cc1483dec75569aeb3dcfc25a9
I'll wait to see if all the checks are passing.

**Comment by hmenke** [comment] 2019-04-05 03:49
Fixed in https://github.com/pgf-tikz/pgf/commit/c69793450d9318cc1483dec75569aeb3dcfc25a9

**Closed as completed** 2019-04-05 03:48 UTC
Labels: closed-fixed, node
