### ISSUE TITLE
Shade does not work with standalone and XeLaTeX

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [pgf-tikz/pgf#951] opened 2020-11-22 12:52 UTC
### Brief outline of the bug

I'm facing a problem using `\shade` with the `standalone` class and the `XeLaTeX` engine. I've searched and found [this answer](https://tex.stackexchange.com/a/151599) that claims that the problem should already be solved. The following MWE, if compiled with `pdfLaTeX` produces this image:
![image](https://user-images.githubusercontent.com/9049533/99904131-54f01180-2cc9-11eb-8645-ae219da9733c.png) 

but when compiling with `XeLaTeX` I get a blank image (no warnings/errors however):
![image](https://user-images.githubusercontent.com/9049533/99904175-8cf75480-2cc9-11eb-9ba5-e46f414b42e5.png)

### Minimal working example (MWE)

```latex
\documentclass[tikz]{standalone}
\begin{document}
  \begin{tikzpicture}
    \shade[ball color=green] (0,0) circle (1cm);
  \end{tikzpicture}
\end{document}
```
### Technical details
I'm using MacTeX-2020, fully updated (`pgf` version: 3.1.6a) under macOS 11.0.1.

Any idea what can be happening?

**Comment by hmenke** [comment] 2020-11-22 13:39
Exact duplicate of https://github.com/pgf-tikz/pgf/issues/928.
Please search existing issues before opening a new one.

**Closed as completed** 2020-11-22 13:40 UTC
Labels: closed-duplicate

**Comment by rodrigoalcarazdelaosa** [comment] 2020-11-22 14:12
> Exact duplicate of https://github.com/pgf-tikz/pgf/issues/928.
> 
> Please search existing issues before opening a new one.

I assure you that I searched but didn't find anything (probably used a wrong choice of words: `shade`, `standalone`, `xelatex`). From what I read it's already fixed but not yet uploaded to CTAN right? Looking forward to it!
