### ISSUE TITLE
References and Index missing in manual

### ISSUE THREAD

**Issue by schtandard** [pgf-tikz/pgf#674] opened 2019-05-13 21:33 UTC
The manual of the latex release (version 3.1.3) ends on page 1247, which is the title page of Part XI _References and Index_. I guess there should be something more there.

**Comment by hmenke** [comment] 2019-05-13 21:43
Yes, I can confirm that there are some issues with the build system of the manual.  It looks like `makeindex` is only run on an empty `pgfmanual.idx` once, so one would have to call `make` twice which I apparently did not do.

I don't think the missing index is such a problem because I believe it is not frequently used (you can just search the PDF for your keyword).  Nevertheless it will be fixed with the next release.  For now I will rebuild the manual and make it available through GitHub releases.

**Comment by hmenke** [comment] 2019-05-13 21:52
Manual with index is available from here now:
https://github.com/pgf-tikz/pgf/releases/download/3.1.3/pgfmanual.pdf

**Comment by hmenke** [comment] 2019-05-24 03:33
Fixed in https://github.com/pgf-tikz/pgf/commit/f46a7419b0ed3461abe6110d8442e86484524f65

**Closed as completed by hmenke** 2019-05-24 03:33 UTC
Labels: closed-fixed, manual

**Comment by hmenke** [comment] 2019-07-11 03:39
The latest upstream PDF manual is now generated automatically and made available at http://pgf-tikz.github.io/pgf/pgfmanual.pdf
