### ISSUE TITLE
pgfpicture environments do not work with tex4ht driver

### ISSUE THREAD

**Issue by dcpurton** [pgf-tikz/pgf#663] opened 2019-04-22 06:16 UTC
I can't get anything to work inside a `pgfpicture` environment with the `tex4ht` driver. `dvisvgm` is fine.

Running this with `htlatex` produces an empty `\jobname-1.svg` file and the HTML file doesn't even reference `\jobname-1.svg` at all.

```TeX
\documentclass{article}
%\def\pgfsysdriver{pgfsys-dvisvgm.def}% works
\def\pgfsysdriver{pgfsys-tex4ht.def}
\usepackage{pgf}
\begin{document}
\begin{pgfpicture}
  \pgfpathrectangle{\pgfpointorigin}{\pgfpoint{2cm}{1cm}}
  \pgfusepath{stroke}
\end{pgfpicture}
\end{document}
```

**Comment by hmenke** [comment] 2019-04-22 06:19
https://github.com/michal-h21/dvisvgm4ht

Duplicate of https://github.com/pgf-tikz/pgf/issues/651?

**Comment by dcpurton** [comment] 2019-04-22 06:33
It works with he `dvisvgm4ht` driver but not with `tex4ht-updated`.

You can make it a duplicate if you want, but "manual doesn't build" is pretty generic :). I guess it depends on whether you are resigned to `tex4ht` being broken for the time being. If so, I won't bother testing things with it.

**Comment by hmenke** [comment] 2019-04-22 06:35
Well, the only testcase we currently have is the manual and since that doesn't build with `tex4ht`, we can't test it at all.

**Closed as completed** 2019-04-22 06:36 UTC
Labels: tex4ht
