### ISSUE TITLE
Missing character under XeTeX

### ISSUE THREAD

**Issue by kvafa** [pgf-tikz/pgf#1167] opened 2022-06-12 04:59 UTC
### Brief outline of the bug

When using `\useoutertheme{shadow}` in beamer under XeTeX, one gets the following unpleasant info in the log:

````tex
Missing character: There is no 2 ("32) in font nullfont!
Missing character: There is no 2 ("32) in font nullfont!
````
This does not happen with PDFTeX so I assume it is engine dependent.

### Minimal working example (MWE)

````tex
\documentclass{article}
\usepackage{pgf}
\pgfdeclareverticalshading{vafak}{2\paperwidth}{%
  color(0pt)=(pgftransparent!100);
  color(8pt)=(pgftransparent!0)
}
\pgfdeclarefading{vafa}{\pgfuseshading{vafak}}
\begin{document}
  \begin{pgfpicture}
    \pgfpathrectangle{\pgfpoint{0pt}{-4pt}}{\pgfpoint{\paperwidth}{4pt}}%
    \pgfsetfading{vafa}{}%
    \pgfusepath{fill}%
  \end{pgfpicture}
\end{document}
````

**Comment by muzimuzhi** [comment] 2022-06-12 07:08
duplicate of #1088, which has been resolved but is not yet released. You can find a workaround in #1088.

**Closed as completed by muzimuzhi** 2022-06-12 07:08 UTC
Labels: closed-duplicate
