### ISSUE TITLE
Second argument for `.code 2 args` is not optional

### ISSUE THREAD

**Issue by fritzw** [pgf-tikz/pgf#1010] opened 2021-04-29 14:32 UTC
In section "87.4.3 Defining Key Codes" under `.code 2 args`, the manual states: 

> The second argument is optional: if it is not provided, it will be the empty string. Because of the special way the 'value' is parsed, if you set 'value' to, for instance, first (without any braces), then `#1` will be set to f and `#2` will be set to irst.

This appears to be false. If you pass a single braced argument, pgfkeys will always parse the first character as `#1` and the rest as `#2`, even if you use double braces. Only when using triple braces, does it work as advertised in the manual.

**Minimal working example (MWE)**

```latex
\documentclass{article}
\usepackage{tikz}

\tikzset{
	my plain key/.code 2 args={1=#1, 2=#2},
}

\begin{document}
\pgfkeys{/tikz/my plain key={Expected result}{}}

\pgfkeys{/tikz/my plain key={First only}}

\pgfkeys{/tikz/my plain key={First}{Second}}

\pgfkeys{/tikz/my plain key={{Double Braces}}}

\pgfkeys{/tikz/my plain key={{{Triple Braces}}}}
\end{document}
```

**Result:**

![image](https://user-images.githubusercontent.com/3628933/116567966-65578880-a908-11eb-81d0-ea41a3a51cec.png)

**Comment by hmenke** [comment] 2021-04-29 14:34
Exact duplicate of https://github.com/pgf-tikz/pgf/issues/991. Please search existing issues before opening a new one.

**Closed as completed by hmenke** 2021-04-29 14:34 UTC
Labels: closed-duplicate

**Comment by fritzw** [comment] 2021-04-29 14:50
Sorry, I did a search for "code 2 args" but that did not turn up anything. Obviously I forgot to search for closed issues as well. :-(
