### ISSUE TITLE
Wrong internal link in pgfmanual-en-tikz-plots.tex: the link for the `scale` key goes not to the correct part of the manual

### ISSUE THREAD

**Issue by quark67** [pgf-tikz/pgf#1118] opened 2021-12-21 00:26 UTC
Version: 3.1.9a

On line 241 of pgf/doc/generic/pgf/pgfmanual-en-tikz-plots.tex (https://github.com/pgf-tikz/pgf/blob/21310438ae418e15ea92b2845a866554202d13d7/doc/generic/pgf/pgfmanual-en-tikz-plots.tex)

we read:

```
\tikz \draw[scale=0.5,domain=-3.141:3.141,smooth,variable=\t]
```

On the manual (page 345), the internal link of the key `scale` goes to the page 196:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/9338576/146849447-27b008c0-0eef-4d67-be38-00da2fd4a6a9.png">

But page 196 is about **arrows** *scale* key (/pgf/arrows keys/scale).

The correct page for the key *scale* is rather page 377 (for /tikz/scale), about Coordinate Transformations.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/9338576/146850059-e8f42acf-6bfd-4706-be28-3551ca96744f.png">

It's perhaps difficult to correct this as the link seems to be added automatically by the detection of the key `scale` but there is multiple `scale` keys (for /pgf/arrows keys or for /tikz). I hope you can find a solution.

**Comment by muzimuzhi** [comment] 2021-12-21 00:40
duplicate of #495

**Comment by hmenke** [comment] 2021-12-21 07:56
The link is definitely “correct”. After all it points to a key called `scale`. It's just not the one you want it to point to.

**Closed as completed** 2021-12-21 07:56 UTC
Labels: closed-duplicate, manual

**Comment by polgab** [comment] 2022-01-13 23:09
@hmenke You definitely can't write (even ironically) that the link is "correct"... The `/tikz/scale` key is NOT the `/tikz/arrow keys/scale` key !!!

**Comment by hmenke** [comment] 2022-01-14 08:11
@polgab The codeexample parser only sees unqualified keys (i.e. the part after the last slash) and from this perspective both of these links are equally correct. I don't see an easy solution here except for writing the fully qualified names at all times, i.e. `\draw[/tikz/scale=0.5]`, but that will make the manual quite unreadable and is too much of an effort.

**Comment by polgab** [comment] 2022-01-30 09:34
The `scale` key is mentioned about 52 times in the examples of the manual. Each time, the `/tikz/scale` key is the correct link except in the three examples on page 196 (16.3.2 Scaling). However, currently, all point to the key `/tikz/arrows keys/scale`... There are therefore 6 correct links for 46 incorrect ones !

The solution may be to not make the `/tikz/arrow keys/scale` key referenceable at all!

**Comment by hmenke** [comment] 2022-01-30 11:03
I have been made aware of the issue multiple times now. Unless you can provide an actual solution please stop complaining.
