### ISSUE TITLE
The manual on CTAN does not have an index

### ISSUE THREAD

**Issue by juliangilbey** [pgf-tikz/pgf#687] opened 2019-06-02 09:41 UTC
Hello!

The version of pgf on CTAN (cat-version: 3.1.3, cat-date: 2019-05-09 21:05:53 +0200) does not have an index - it just finishes on page 1247 with the index title page.  Perhaps something went wrong with the index construction?

Best wishes,

Julian

**Comment by hmenke** [comment] 2019-06-02 09:59
Duplicate of https://github.com/pgf-tikz/pgf/issues/674
Please search existing issues first before opening a new one.

**Closed as completed by hmenke** 2019-06-02 09:59 UTC
Labels: closed-duplicate

**Comment by juliangilbey** [comment] 2019-06-04 08:29
Sorry for the duplicate; I didn't see the closed report when I searched github for related issues.
Thanks for fixing it!
