### ISSUE TITLE
pgfcalendar: Translation of month and weekday names is broken?

### ISSUE THREAD

**Issue by paternal** [pgf-tikz/pgf#725] opened 2019-08-04 11:43 UTC
Hello,
I use the pgfcalendar package to build a calendar (in French), but the month and weekday names are no longer translated. Here is a MWE.

~~~latex
\documentclass[french]{article}

\usepackage{babel}
\usepackage{translator}
\usepackage{pgfcalendar}

\begin{document}

\section{Direct call to translator}

\translate{Monday}
\translate{January}

\section{Calls using pgfcalendar}

\pgfcalendarweekdayname{0}
\pgfcalendarmonthname{1}

\end{document}
~~~

The names in the first section are translated,  using command `\translate` from package translator. However, the names in the second section are not, although the pgf/tikz translation states that *"All textual representations of week days or months (like “Monday” or “February”) are wrapped with \translate commands from the translator package"*.

Is this a regression, or am I using something wrong?

Thanks for your work,    
-- Louis

**Comment by hmenke** [comment] 2019-08-04 21:14
Exact duplicate of https://github.com/pgf-tikz/pgf/issues/689
Please search existing issues first before opening a new one.

**Closed as completed by hmenke** 2019-08-04 21:14 UTC
Labels: closed-duplicate, calendar

**Comment by paternal** [comment] 2019-08-05 06:28
Sorry. I had seen this issue, but I do not know it was the same as this one (I do not understand the internals of PGF/TiKZ).

-- Louis
