### ISSUE TITLE
External library does not completely turn off dash pattern

### ISSUE THREAD

**Issue by kjgoodrick** [pgf-tikz/pgf#841] opened 2020-03-21 23:24 UTC
When using the external library, for some reason dash patterns are not turned off completely. This is imperceptible under normal circumstances, but when uploading figures to Manuscript Central it reveals itself. 

Consider the MWE below which draws a short dashed line and then a solid line and externalizes it. The generated pdf looks as expected:

<img src="https://user-images.githubusercontent.com/1909532/77238591-3a442680-6b97-11ea-894f-4b291017c11e.png" width="300">

However, after uploading the pdf to Manuscript Central (Specifically the Manuscript Central for IEEE Transactions on Power Electronics, but I imagine any would do it.) Both lines are dashed:

<img src="https://user-images.githubusercontent.com/1909532/77238624-97d87300-6b97-11ea-904d-9bd0181d886a.png" width="300">

After disabling the external library this behavior disappears. It may also be fixed by explicitly setting the `solid` style for the second draw command.

**Minimal working example (MWE)**

```latex
\documentclass[margin=1cm]{standalone}
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize

\begin{document}
\begin{tikzpicture}
  \draw[dashed] (0,1) -- (1,1);
  \draw (0,0) -- (1,0);
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment] 2020-03-22 00:16
I can't reproduce this in any engine or any viewer, so IEEE is likely doing something nonstandard-confirming to the PDF before handing it back to you.

Which engine are you using?
```
evince |          mupdf
okular | Google Chrome | Firefox
```
![test](https://user-images.githubusercontent.com/1903556/77239384-0d4b4e80-6c3f-11ea-9afc-98cde137fa06.png)

**Comment by hmenke** [comment] 2020-03-22 01:19
Maybe related #833

**Comment by kjgoodrick** [comment] 2020-03-22 02:58
Yeah, the problem is only visible after uploading it to Manuscript Central and then downloading the PDF proof. The proof has line numbers, page numbers, and a header added. I wouldn't be surprised if they were doing something weird to add those, it's weird that it only happens with external mode though. 

I am using pdfTeX, specifically Version 3.14159265-2.6-1.40.21 (MiKTeX 2.9.7300 64-bit). 

If it's useful to you I've attached 6 pdfs:

[solid_external_pre_mc.pdf](https://github.com/pgf-tikz/pgf/files/4364563/solid_external_pre_mc.pdf)
[normal_post_mc.pdf](https://github.com/pgf-tikz/pgf/files/4364564/normal_post_mc.pdf)
[normal_pre_mc.pdf](https://github.com/pgf-tikz/pgf/files/4364565/normal_pre_mc.pdf)
[external_post_mc.pdf](https://github.com/pgf-tikz/pgf/files/4364566/external_post_mc.pdf)
[external_pre_mc.pdf](https://github.com/pgf-tikz/pgf/files/4364567/external_pre_mc.pdf)
[solid_external_post_mc.pdf](https://github.com/pgf-tikz/pgf/files/4364568/solid_external_post_mc.pdf)

Three are the pdfs produced by (a) normal tikz (i.e. no external) (b) externalized tikz (c) externalized tikz with explicitly set solid style for the second line. The other three are the same pdfs after being run through manuscript central.

**Comment by hmenke** [comment] 2020-03-22 03:03
Sorry, but there is no way for me to support some obscure proprietary renderer that I don't have access to, so I'm closing this for now.

I will of course reopen this if you can come up with a reliable route through which I can reproduce it on GNU/Linux x86_64.

**Comment by hmenke** [comment] 2020-03-22 03:51
Maybe we can at least do some guesswork.  Could you please give this a try?  This will use LaTeX's `\includegraphics` to include the externalized image instead of PGF's `\pgfimage`.
```latex
\documentclass[margin=1cm]{standalone}
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize
\pgfkeys{/pgf/images/include external/.code={\includegraphics{#1}}}

\begin{document}
\begin{tikzpicture}
  \draw[dashed] (0,1) -- (1,1);
  \draw (0,0) -- (1,0);
\end{tikzpicture}
\end{document}
```

**Comment by kjgoodrick** [comment] 2020-03-22 20:12
I completely understand the difficulty in figuring this one out and I think that it is probably more of a problem with manuscript central than with pgf. Unfortunately, manuscript central is not obscure; it's widely used by academic journals, which I believe is the primary target for most pgf users. It also appears that there is something tikz is doing that causes this, even if what tikz is doing is "correct" and manuscript central is wrong. 

I tried the code given in your last comment and it has the same behavior as the default `\pgfimage`. 

I also tried uncompressing the generated pdfs (pre manuscript central) and I think I have found what the difference is between the two. If you take the primary stream and the inserted stream and line them up with the non-external stream there is one line in the external version that is not present in the normal version (Along with a couple lines that have swapped places). 

`1 0 0 1 0.199 0.199 cm`

If I had to guess based on the lengths this is specifying a dash pattern. It's unfortunately mostly gibberish to me so I can't say anything for certain about it. I've included the diff of the lined up streams below and also attached the full versions.

````diff
--- normal.txt
+++ external.txt
@@ -3,7 +3,10 @@
 0 g 0 G
 0 g 0 G
 0 g 0 G
-1 0 0 1 28.546 28.546 cm
+q
+1 0 0 1 28.346 28.346 cm
+0 g 0 G
+1 0 0 1 0.199 0.199 cm
 q
 0 G
 0 g
@@ -21,6 +24,7 @@
 Q
 n
 Q
+Q
 0 g 0 G
 0 g 0 G
 0 g 0 G
````

[external_pre_mc_un.pdf](https://github.com/pgf-tikz/pgf/files/4366250/external_pre_mc_un.pdf)
[normal_pre_mc_un.pdf](https://github.com/pgf-tikz/pgf/files/4366251/normal_pre_mc_un.pdf)

I appreciate your time looking at this and hope the information above is useful!

**Comment by hmenke** [comment] 2020-03-22 20:59
What did you use to uncompress the PDFs?  I tried to uncompress the PDFs you posted before using `qpdf --stream-data=uncompress in.pdf out.pdf` but that did not uncompress the object streams leaving me with gibbering instead of TikZ pictures.

The `cm` instruction is not the dash pattern.  It's the transformation matrix.  The first four values are the matrix elements (in this case the identity, i.e. no rotation or skewing), the last two are the shift.

**Comment by kjgoodrick** [comment] 2020-03-22 21:47
I used the command `qpdf --qdf --object-streams=disable in.pdf out.pdf`

Interesting, I'm surprised that that being different would change the dash pattern. I also just tried changing the color of the first line as well and that does get turned off, so it's just the dash pattern that stays with the second line.

**Comment by hmenke** [comment] 2020-03-22 22:12
Dash patterns in PDF are marked by `d`.  So a a simple dashed line would have, e.g. `[20] 0 d` for 20bp dashes with dash phase 0 (i.e. on off on off etc.).

**Comment by hmenke** [comment] 2020-03-22 22:13
I'm almost certain that the problem comes from the added `q` / `Q` bracket, but I have to find a way to confirm that.

**Comment by kjgoodrick** [comment] 2020-03-22 22:59
I see, I found the PDF32000 standard and it's been quite helpful! Are you talking about the 

````pdf
n
Q
````

Right before the `endstream` that don't seem to have a matching `q`? I could try removing those two lines manually and see if that fixes it?

**Comment by kjgoodrick** [comment] 2020-03-22 23:16
Removing those lines did not work unfortunately. 

Looking at the post manuscript central uncompressed files it looks like they add a `[]0 d` command to the non-external version after the first line, but not for the external one. Perhaps there's some preprocessing that they do to "base" file that they do not do to the external files? This would unfortunately mean there's nothing we can do to fix it.

**Comment by hmenke** [comment] 2020-03-22 23:35
I analyzed the PDFs you sent earlier and found this:
`external_pre_mc.pdf`
```
0 g 0 G
1 0 0 1 0.199 0.199 cm
q 
0 G 
0 g 
0.3985 w 
q 
q 
[ 2.98883 2.98883 ] 0.0 d 
0.0 28.3468 m 
28.3468 28.3468 l 
S 
Q <--- resets the dash pattern
0.0 0.0 m 
28.3468 0.0 l 
S 
Q 
n 
Q 
```

`external_post_mc.pdf`
```
0 TL
q
0 G
0.3985 w [2.98883 2.98883]0 d 
q
1 0 0 1 0.199 0.199 cm
0 28.3468 m
28.3468 28.3468 l
S
Q
q
Q
q
1 0 0 1 0.199 0.199 cm
0 0 m
28.3468 0 l
S
Q
Q <--- resets the dash pattern
```
The commentary is of course mine.  First of all I note that the PDF stream post MC has very little to do with the stream pre MC, i.e. they completely dissect the PDF and reassemble it, but they break the stack balancing.  As you can see the `Q` that restores the graphic state is missing in the correct position in the post MC version.

I think it is clear now that this is definitely MC's fault.  You might want to contact their support that their service is corrupting valid PDFs.

**Closed as completed by hmenke** 2020-03-22 23:35 UTC
Labels: closed-invalid, external

**Comment by kjgoodrick** [comment] 2020-03-23 00:49
Hi Henri,

I really appreciate you looking into this and I agree that it is certainly their fault. I will get in touch with them and hopefully they will fix things on their side. 

In the meantime, for anyone else that runs into this, I believe an ok workaround is to temporarily disable externalization before uploading to Manuscript Central. If that does not work for some reason you can manually reset the dash pattern in the next path (no need to do it with all) with the `solid` style.

Thanks again,

Kyle

**Comment by letzfets** [comment] 2020-03-23 13:10
I ran the MWE through pdflatex, and uploaded the main.pdf to IEEE as a figure. I can't get the proofread version, as I didn't fill in the rest of the stuff, necessary to "simulate a submission". But maybe @kjgoodrick you can upload my main.pdf?

[main.pdf](https://github.com/pgf-tikz/pgf/files/4369469/main.pdf)

The one I download from IEEE later is this one:
[main-IEEE_download.pdf](https://github.com/pgf-tikz/pgf/files/4369468/main-IEEE_download.pdf)

diff says, those files are completely identical - but again, this si not the reviewer version with the line numbers and so on.

I cannot see the issue in bot of my viewers: preview and skim on a Mac.

Cheers

**Comment by kjgoodrick** [comment] 2020-03-23 16:46
Yeah, the pdf is fine if you download from the HTML proof, it's only after it goes through their process that adds the line numbers and header page that it gets corrupted.
