### ISSUE TITLE
Using controls and cycle in a named picture leads to “no shape … known” error.

### ISSUE THREAD

**Issue by Wrzlprmft** [pgf-tikz/pgf#717] opened 2019-07-23 14:00 UTC
Minimal example:
``` TeX
\documentclass{standalone}
\usepackage{tikz}

\tikzset{pics/mypic/.style={code={
	\draw (0,0) .. controls (1,1) .. cycle;
}}}

\begin{document}
	\begin{tikzpicture}
		\pic (myname) {mypic};
	\end{tikzpicture}
\end{document}
```

This raises the following error:
```
! Package pgf Error: No shape named mynamecurrent subpath start is known.

See the pgf package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.10 		\pic (myname) {mypic}
                            ;
```

The following changes remove the problem:

* Using `--` instead of `controls`.
* Using `(0,0)` instead of `cycle`.
* Not naming the picture, i.e., removing `myname`.

**Comment by hmenke** [comment] 2019-07-27 01:16
What I find most interesting is that this works at all.  I always thought that the only legal construction that you could use was `-- cycle;`.  Does it work if the `pic` content is
```latex
\draw (0,0) .. controls (1,1) .. (0,0) -- cycle;
```

**Comment by Wrzlprmft** [comment] 2019-07-27 07:57
> Does it work if the `pic` content is
> 
> ```
> \draw (0,0) .. controls (1,1) .. (0,0) -- cycle;
> ```

Yes, that throws no error.

**Comment by hmenke** [comment] 2019-11-03 22:21
Short investigation shows that this is most likely a duplicate of https://github.com/pgf-tikz/pgf/issues/311

**Closed as completed** 2019-11-04 06:28 UTC
Labels: closed-fixed
