### ISSUE TITLE
external + "path fading" + xelatex -> broken

### ISSUE THREAD

**Issue by letzfets** [pgf-tikz/pgf#833] opened 2020-02-13 18:37 UTC
see here: https://tex.stackexchange.com/questions/326756/tikz-externalize-breaks-path-fading
The combination of the 3 above breaks the path fading command for all fadings, that are user defined, e.g. through `\tikzfading`

**Comment by letzfets** [comment] 2020-02-13 18:40
As a workaround the `\shade[]` command works. Might do the job, as long as the fadings are not complicated.

**Comment by hmenke** [comment] 2020-02-13 19:22
No MWE.  What's wrong with using the issue template?

**Comment by letzfets** [comment] 2020-02-13 23:32
Here we go:

Contents of file `main.tex`:
````latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{fadings,external}
\tikzexternalize[prefix=figures/]
\begin{document}
\begin{tikzpicture}[scale=0.7]
  \fill[purple, path fading=west]
  (0,-.1) -- (5,-.1) -- (5,-.2) -- (5.5,0) -- (5,.2) -- (5,.1) -- (0,.1) -- (0,-.1);
  \fill[blue!50, path fading=west]
  (7,-.1) -- (12,-.1) -- (12,-.2) -- (12.5,0) -- (12,.2) -- (12,.1) -- (7,.1) -- (7,-.1);
\end{tikzpicture}
\end{document}
````

I compiled with both `xelatex -shell-escape main` and with `pdflatex -shell-escape main`. Result is the same: the two faded arrows are showing up in the file `figures/main-figure0.pdf`, but not in `main.pdf`.

When I comment the line `\tikzexternalize[prefix=figures/]`, everything is fine.

**Comment by hmenke** [comment] 2020-02-14 01:45
Can't reproduce.  Either your viewer is broken or this is a duplicate of #824.

**Comment by letzfets** [comment] 2020-02-14 09:09
I checked. #824 works fine on my machine. No problem.

As viewers, I've used
skim Version 1.5.6 (122) and
preview Version 11.0 (999.4)
both on my Mac - none of them work.

Other potentially relevant system information:
pgf 3.1.5b
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019)
macOS Catalina 10.15.3 (19D76)

I've also checked if it matters, wether I've got the Mac in dark scheme or light scheme mode (this had implications in other software before). But no.

What else do you need to reopen this as a bug. I'm willing to help - just got pretty frustrated yesterday about the fadings (spent too much time on it).
Please let me know, what I can do for you to help you improve pgf!

Keep up the good work.

**Comment by letzfets** [comment] 2020-02-14 09:21
I've viewed the main.pdf file now on my Android phone with Adobe Acrobat 20.0.1.11139.
Both arrows show up there wonderfully. So keep closed here. This indicates, that it is a viewer issue.

**Comment by hmenke** [comment] 2020-02-14 10:49
I think this is a duplicate of #824.  Unfortunately, it's really unclear what is wrong with the fadings in XeTeX at the PDF level.

**Comment by hmenke** [comment] 2020-02-17 04:08
Discussion on #824 revealed that this might not be the same problem.  I'm happy to fix this but I need a reliable route through which I can reproduce this.  Since I am on GNU/Linux x86_64 it can't involve Adobe Reader (or anything else that doesn't run on Linux).

**Comment by Mo-Gul** [comment] 2020-02-17 06:49
For the record: Using Windows/MiKTeX, compiling with pdflatex and lualatex the above MWE works perfectly fine, both showing in SumatraPDF and Acrobat Reader.

**Comment by letzfets** [comment] 2020-02-17 13:57
> Discussion on #824 revealed that this might not be the same problem. I'm happy to fix this but I need a reliable route through which I can reproduce this. Since I am on GNU/Linux x86_64 it can't involve Adobe Reader (or anything else that doesn't run on Linux).

Skim and Preview are not Adobe either. ;-)
Hmmm, How can I help?!? What viewer are you using? I might be able to install this one on my Mac and we'll take it from there?!?

**Comment by hmenke** [comment] 2020-02-24 21:10
Skim and Preview don't run on GNU/Linux.  I'm mostly using Evince and Zathura, but anything poppler- or mupdf-based should do.  The pdf.js viewer which comes with Firefox is also a possibility.

**Comment by letzfets** [comment] 2020-03-06 08:24
I was trying out the comment from @ilayn on #824 today (change from 50 to 100), but it had no effect on this one.
I thought it might be helpful for further debugging, to provide you with the pdf's, where
- main-figure0.pdf is the one in the subfolder externalised,
- main.pdf is the main document with externalisation in subfolder figures
- main_no_subfolder.pdf is the main document, where I commented the line `\tikzexternalize[prefix=figures/]`:

[main-figure0.pdf](https://github.com/pgf-tikz/pgf/files/4297218/main-figure0.pdf)
[main.pdf](https://github.com/pgf-tikz/pgf/files/4297219/main.pdf)
[main_no_subfolder.pdf](https://github.com/pgf-tikz/pgf/files/4297231/main_no_subfolder.pdf)

I ran a diff -a on those files and surprisingly the main.pdf and the main_no_subfolder.pdf give me an awful lots of hits (which might be due to a shift in the beginning of the document). My intuition tells me, that those files should ideally be exactly the same.

Hmm, the mystery continues! :wink:

**Comment by hmenke** [comment] 2020-03-06 08:42
Since I don't know what I'm looking for and I have no way of reproducing this, I don't have any use for these PDFs.
Also including a drawing is not the same as including a PDF with that drawing.  There is a lot more stuff going on, like embedding of xref tables, etc.

**Comment by hmenke** [comment] 2020-03-22 01:20
@letzfets Could you have a look at #841 and see whether you can reproduce it?  I have a feeling that this is related.

**Comment by hmenke** [comment] 2020-03-22 03:44
I have a hint here.  The XeTeX driver is the only one that falls back on `\includegraphics` for `\pgfimage` (which is used to include externalized pictures).
https://github.com/pgf-tikz/pgf/blob/357bc05926a057f7c1fcbc95877fc508723ac105/tex/generic/pgf/systemlayer/pgfsys-xetex.def#L31-L45

Here I have manually patched out the `\includegraphics` variant.  @letzfets Can you try with this please?
```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{fadings,external}
\tikzexternalize[prefix=figures/]

\makeatletter
\def\pgfsys@defineimage{% width, height, page number
    \PackageWarning{pgf}{Using modified \string\pgfsys@defineimage}%
    \ifx\pgf@imagewidth\pgfutil@empty\edef\pgf@imagewidth{1bp}\fi% width?
    \ifx\pgf@imageheight\pgfutil@empty\edef\pgf@imageheight{1bp}\fi% height?
    \ifx\pgf@imagepage\pgfutil@empty\else\edef\pgf@imagepage{ page \pgf@imagepage}\fi%
    \ifx\pgf@imageinterpolate\pgfutil@empty\else\edef\pgf@imageinterpolate{ /Interpolate\space\pgf@imageinterpolate}\fi%
    \ifx\pgf@imagemask\pgfutil@empty\else\xdef\pgf@imagemask{ /SMask @\pgf@imagemask}\fi%
    \edef\pgf@image{\noexpand\hbox to \pgf@imagewidth{\vbox to \pgf@imageheight{\vfil\special{pdf:image width \pgf@imagewidth\space height \pgf@imageheight\space\pgf@imagepage\space(\pgf@filename) <<\pgf@imageinterpolate\pgf@imagemask\space>>}}\hfil}}%
}
\makeatother

\begin{document}
\begin{tikzpicture}[scale=0.7]
  \fill[purple, path fading=west]
  (0,-.1) -- (5,-.1) -- (5,-.2) -- (5.5,0) -- (5,.2) -- (5,.1) -- (0,.1) -- (0,-.1);
  \fill[blue!50, path fading=west]
  (7,-.1) -- (12,-.1) -- (12,-.2) -- (12.5,0) -- (12,.2) -- (12,.1) -- (7,.1) -- (7,-.1);
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment] 2020-03-22 21:24
@letzfets I'm a bit sceptical of your subfolder vs. no subfolder assessment, because for me the PDFs don't differ apart from the time stamp and the font map.  Before compiling I added `\special{dvipdfmx:config z 0}` before `\documentclass` to generate uncompressed PDF.
```diff
--- subfolder.pdf	2020-03-23 10:17:05.582867057 +1300
+++ no-subfolder.pdf	2020-03-23 10:16:51.242867105 +1300
@@ -147,7 +147,7 @@
 /CIDInit /ProcSet findresource begin
 12 dict begin
 begincmap
-/CMapName /BWSVNT+LMRoman10-Regular-UTF16 def
+/CMapName /LEBKJA+LMRoman10-Regular-UTF16 def
 /CMapType 2 def
 /CIDSystemInfo <<
   /Registry (Adobe)
@@ -170,7 +170,7 @@
 52 0 obj
 <</Subtype/CIDFontType0C/Length 548>>
 stream
-BWSVNT+LMRoman10-RegularE���
                             ��� �!�&
                                     �
                                      �B��������
                                                "�
                                                  $�
                                                    %$��LMRoman10-RegularAdobeIdentity2.004Copyright 2003, 2009 B. Jackowski and J. M. Nowacki (on behalf of TeX users groups). This work is released under the GUST Font License --  see http://tug.org/fonts/licenses/GUST-FONT-LICENSE.txt for details.LMRoman10NormalRK����������w�p��7�k1��������tKM3�k�Ƌ����g�1kl��⋳⋈��
                                                               �u��C��n���
+LEBKJA+LMRoman10-RegularE���
                             ��� �!�&
                                     �
                                      �B��������
                                                "�
                                                  $�
                                                    %$��LMRoman10-RegularAdobeIdentity2.004Copyright 2003, 2009 B. Jackowski and J. M. Nowacki (on behalf of TeX users groups). This work is released under the GUST Font License --  see http://tug.org/fonts/licenses/GUST-FONT-LICENSE.txt for details.LMRoman10NormalRK����������w�p��7�k1��������tKM3�k�Ƌ����g�1kl��⋳⋈��
                                                               �u��C��n���
 To
   	�

         �
 �
  ������������

              ������������

 endstream
@@ -208,17 +208,17 @@
 <</pgfprgb[/Pattern/DeviceRGB]>>
 <</Resources 48 0 R/Type/Page/Parent 49 0 R/Contents[47 0 R]>>
 <</Type/Pages/Count 1/Kids[3 0 R]/MediaBox[0 0 612 792]>>
-<</Creator( XeTeX output 2020.03.23:1017)/Producer(xdvipdfmx \(20200315\))/CreationDate(D:20200323101705+14'00')>>
+<</Creator( XeTeX output 2020.03.23:1016)/Producer(xdvipdfmx \(20200315\))/CreationDate(D:20200323101637+14'00')>>
 <</Pages 49 0 R/Type/Catalog>>
 [82[500]]
-<</Type/Font/Subtype/CIDFontType0/BaseFont/BWSVNT+LMRoman10-Regular/CIDSystemInfo<</Registry(Adobe)/Ordering(Identity)/Supplement 0>>/FontDescriptor 51 0 R/DW 280/W 53 0 R>>
-<</Type/FontDescriptor/Ascent 806/Descent -194/StemV 69/CapHeight 806/AvgWidth 549/FontBBox[-430 -290 1417 1127]/ItalicAngle 0/Flags 6/Style<</Panose<000000000500000000000000>>>/FontName/BWSVNT+LMRoman10-Regular/FontFile3 52 0 R/CIDSet 54 0 R>>
-<</Type/Font/Subtype/Type0/BaseFont/BWSVNT+LMRoman10-Regular-Identity-H/Encoding/Identity-H/DescendantFonts[45 0 R]/ToUnicode 50 0 R>>
+<</Type/Font/Subtype/CIDFontType0/BaseFont/LEBKJA+LMRoman10-Regular/CIDSystemInfo<</Registry(Adobe)/Ordering(Identity)/Supplement 0>>/FontDescriptor 51 0 R/DW 280/W 53 0 R>>
+<</Type/FontDescriptor/Ascent 806/Descent -194/StemV 69/CapHeight 806/AvgWidth 549/FontBBox[-430 -290 1417 1127]/ItalicAngle 0/Flags 6/Style<</Panose<000000000500000000000000>>>/FontName/LEBKJA+LMRoman10-Regular/FontFile3 52 0 R/CIDSet 54 0 R>>
+<</Type/Font/Subtype/Type0/BaseFont/LEBKJA+LMRoman10-Regular-Identity-H/Encoding/Identity-H/DescendantFonts[45 0 R]/ToUnicode 50 0 R>>
 
 endstream
 endobj
 55 0 obj
-<</Type/XRef/Root 1 0 R/Info 2 0 R/ID[<61e8d4d859077a8ab99a55e220ca1d63><61e8d4d859077a8ab99a55e220ca1d63>]/Size
+<</Type/XRef/Root 1 0 R/Info 2 0 R/ID[<71e674aaaace65cb00ec7dc3d173a162><71e674aaaace65cb00ec7dc3d173a162>]/Size
 56/W[1 2 2]/Length 280>>
 stream
 ���C�{Y7�	m
```

**Comment by hmenke** [comment] 2020-03-22 23:59
I have downloaded the `main.pdf` and `main_no_subfolder.pdf` you posted earlier and uncompressed both using
```console
$ qpdf --qdf --object-streams=disable main.pdf main_un.pdf
$ qpdf --qdf --object-streams=disable main_no_subfolder.pdf main_no_subfolder_un.pdf
```
Then I deleted everything apart from the stream that renders the picture and diff-ed the result with  `git diff --no-index --word-diff main_un.pdf main_no_subfolder_un.pdf`
```diff
--- a/main_un.pdf
+++ b/main_no_subfolder_un.pdf
@@ -1 +1 @@
 q 1 0 0 1 72 [--64.063-]{+720+} cm q 1 0 0 1 [--72 68.032-]{+76.712 -58.796+} cm q  0 G  0 g  0.3985 w  q  q  0.75 0 0.25 RG 0.75 0 0.25 rg 2.19131 0.0 0.0 0.15936 -54.99976 -7.96823 cm  /pgfsmask6 gs 0.4564 0.0 0.0 6.27516 25.10219 50.00197 cm  0.0 -1.98438 m  99.2134 -1.98438 l  99.2134 -3.96846 l  109.13472 0.0 l  99.2134 3.96846 l  99.2134 1.98438 l  0.0 1.98438 l  0.0 -1.98438 l  f  0 G 0 g Q  q  0.5 0.5 1 RG 0.5 0.5 1 rg 2.19131 0.0 0.0 0.15936 83.89897 -7.96823 cm  /pgfsmask6 gs 0.4564 0.0 0.0 6.27516 -38.29195 50.00197 cm  138.89876 -1.98438 m  238.11215 -1.98438 l  238.11215 -3.96846 l  248.03348 0.0 l  238.11215 3.96846 l  238.11215 1.98438 l  138.89876 1.98438 l  138.89876 -1.98438 l  f  0 G 0 g Q  Q  n  Q  Q {+BT /F1 9.9626 Tf 231.133 -630.635 Td[<0052>]TJ ET+} Q
```
The only things that are different are the shifts in the transformation and the presence of the text object which is in a different stream in `main.pdf`.  I think this is most likely a bug in the viewer (which is also why I can't reproduce it) and you report it there.

**Comment by letzfets** [comment] 2020-03-23 13:12
> @letzfets Could you have a look at #841 and see whether you can reproduce it? I have a feeling that this is related.

I've replied in #841 , no I cannot reproduce it, sorry

**Comment by letzfets** [comment] 2020-03-23 13:20
> I have a hint here. The XeTeX driver is the only one that falls back on `\includegraphics` for `\pgfimage` (which is used to include externalized pictures).
> 
> https://github.com/pgf-tikz/pgf/blob/357bc05926a057f7c1fcbc95877fc508723ac105/tex/generic/pgf/systemlayer/pgfsys-xetex.def#L31-L45
> 
> Here I have manually patched out the `\includegraphics` variant. @letzfets Can you try with this please?
> 
> ```
> \documentclass{article}
> \usepackage{tikz}
> \usetikzlibrary{fadings,external}
> \tikzexternalize[prefix=figures/]
> 
> \makeatletter
> \def\pgfsys@defineimage{% width, height, page number
>     \PackageWarning{pgf}{Using modified \string\pgfsys@defineimage}%
>     \ifx\pgf@imagewidth\pgfutil@empty\edef\pgf@imagewidth{1bp}\fi% width?
>     \ifx\pgf@imageheight\pgfutil@empty\edef\pgf@imageheight{1bp}\fi% height?
>     \ifx\pgf@imagepage\pgfutil@empty\else\edef\pgf@imagepage{ page \pgf@imagepage}\fi%
>     \ifx\pgf@imageinterpolate\pgfutil@empty\else\edef\pgf@imageinterpolate{ /Interpolate\space\pgf@imageinterpolate}\fi%
>     \ifx\pgf@imagemask\pgfutil@empty\else\xdef\pgf@imagemask{ /SMask @\pgf@imagemask}\fi%
>     \edef\pgf@image{\noexpand\hbox to \pgf@imagewidth{\vbox to \pgf@imageheight{\vfil\special{pdf:image width \pgf@imagewidth\space height \pgf@imageheight\space\pgf@imagepage\space(\pgf@filename) <<\pgf@imageinterpolate\pgf@imagemask\space>>}}\hfil}}%
> }
> \makeatother
> 
> \begin{document}
> \begin{tikzpicture}[scale=0.7]
>   \fill[purple, path fading=west]
>   (0,-.1) -- (5,-.1) -- (5,-.2) -- (5.5,0) -- (5,.2) -- (5,.1) -- (0,.1) -- (0,-.1);
>   \fill[blue!50, path fading=west]
>   (7,-.1) -- (12,-.1) -- (12,-.2) -- (12.5,0) -- (12,.2) -- (12,.1) -- (7,.1) -- (7,-.1);
> \end{tikzpicture}
> \end{document}
> ```

I've ran your patch both through xelatex and pdflatex. It does not solve the problem.
Remember: in my case the problem shows up regardless of which of those two compilers I use.

Cheers

**Comment by letzfets** [comment] 2020-03-23 13:29
> I have downloaded the `main.pdf` and `main_no_subfolder.pdf` you posted earlier and uncompressed both using
> 
> ```
> $ qpdf --qdf --object-streams=disable main.pdf main_un.pdf
> $ qpdf --qdf --object-streams=disable main_no_subfolder.pdf main_no_subfolder_un.pdf
> ```
> 
> Then I deleted everything apart from the stream that renders the picture and diff-ed the result with `git diff --no-index --word-diff main_un.pdf main_no_subfolder_un.pdf`
> 
> ```diff
> --- a/main_un.pdf
> +++ b/main_no_subfolder_un.pdf
> @@ -1 +1 @@
>  q 1 0 0 1 72 [--64.063-]{+720+} cm q 1 0 0 1 [--72 68.032-]{+76.712 -58.796+} cm q  0 G  0 g  0.3985 w  q  q  0.75 0 0.25 RG 0.75 0 0.25 rg 2.19131 0.0 0.0 0.15936 -54.99976 -7.96823 cm  /pgfsmask6 gs 0.4564 0.0 0.0 6.27516 25.10219 50.00197 cm  0.0 -1.98438 m  99.2134 -1.98438 l  99.2134 -3.96846 l  109.13472 0.0 l  99.2134 3.96846 l  99.2134 1.98438 l  0.0 1.98438 l  0.0 -1.98438 l  f  0 G 0 g Q  q  0.5 0.5 1 RG 0.5 0.5 1 rg 2.19131 0.0 0.0 0.15936 83.89897 -7.96823 cm  /pgfsmask6 gs 0.4564 0.0 0.0 6.27516 -38.29195 50.00197 cm  138.89876 -1.98438 m  238.11215 -1.98438 l  238.11215 -3.96846 l  248.03348 0.0 l  238.11215 3.96846 l  238.11215 1.98438 l  138.89876 1.98438 l  138.89876 -1.98438 l  f  0 G 0 g Q  Q  n  Q  Q {+BT /F1 9.9626 Tf 231.133 -630.635 Td[<0052>]TJ ET+} Q
> ```
> 
> The only things that are different are the shifts in the transformation and the presence of the text object which is in a different stream in `main.pdf`. I think this is most likely a bug in the viewer (which is also why I can't reproduce it) and you report it there.

Well, it might very well be, that both viewers (skim and preview). I've also installed Firefox now, and it's the same result there. Hmm?!?

**Comment by hmenke** [comment] 2020-03-23 20:46
I don't know what exactly you are doing but both arrows show up correctly for me in Firefox 74.0, so this might not even be a viewer issue but some other issue with your specific setup.

![test](https://user-images.githubusercontent.com/1903556/77361245-d8143d00-6db3-11ea-98ea-029e47bf7fe5.png)

Sorry, but if you can't come up with a way for me to reproduce this (that doesn't involve me buying a €2000 MacBook), then I will have to close this.  I'll also ask in the TeX.SX whether anyone can reproduce.

**Comment by hanche** [comment] 2020-03-23 21:50
I can reproduce it on my mac (recent macbook pro, latest macos, TL 2020 pretest).

The resulting pdf has no visible arrows when viewed in skim, preview, or pdfpen pro. However, with mupdf, the arrows are present. So it seems like it could be a viewer issue. I get the same result when compiling on a gnu/linux machine and viewing the result on the mac.

**Comment by letzfets** [comment] 2020-03-23 22:40
Then we have at least 3 computers on this planet, that got this problem. Note, that the original MWE, that I provided was from 2016 here https://tex.stackexchange.com/questions/326756/tikz-externalize-breaks-path-fading
I can try to have a look at my girlfriends MacBook Pro (a few years older hardware and a few MacOS versions older than mine).
Personally I have worked around the issue in my document with the `\shade` command. But I see it as a sporty challenge to find the root of this issue.

**Comment by hmenke** [comment] 2020-03-24 00:00
Reproducing this on more macOS machines doesn't make sense at this point because we already know that Apple's PDF engine fails to render this correctly.  Instead you should try to reproduce this on computers that are *not* running macOS, so you can be sure that the viewer definitely cannot fall back onto Apple's broken PDF engine (which is what might happen for your Firefox).  Furthermore you should also report the bug to Apple and hear what they have to say about it.

**Comment by u-fischer** [comment] 2020-03-24 13:20
@letzfets @hanche  what happens if the shading is in an external *and* in an internal picture?

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{fadings,external}

\begin{document}
\begin{tikzpicture}[scale=0.7]
  \fill[purple, path fading=west]
  (0,-.1) -- (5,-.1) -- (5,-.2) -- (5.5,0) -- (5,.2) -- (5,.1) -- (0,.1) -- (0,-.1);
\end{tikzpicture}


\tikzexternalize[]
\begin{tikzpicture}[scale=0.7]
  \fill[purple, path fading=west]
  (0,-.1) -- (5,-.1) -- (5,-.2) -- (5.5,0) -- (5,.2) -- (5,.1) -- (0,.1) -- (0,-.1);
\end{tikzpicture}
\end{document}
```

**Comment by hanche** [comment] 2020-03-24 15:40
@u-fischer That doesn't work because `\tikzexternalize` has to be called in the preamble. It ends up calling `\nofiles` … and perhaps there are other reasons.

**Comment by u-fischer** [comment] 2020-03-24 15:48
@hanche yes sorry it worked for me (or did what I expected) but probably only because the graphic existed. Can you try this:

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{fadings,external}
\tikzexternalize[]
\begin{document}
\begin{tikzpicture}[scale=0.7]
  \fill[purple, path fading=west]
  (0,-.1) -- (5,-.1) -- (5,-.2) -- (5.5,0) -- (5,.2) -- (5,.1) -- (0,.1) -- (0,-.1);
\end{tikzpicture}

\tikzexternaldisable

\begin{tikzpicture}[scale=0.7]
  \fill[purple, path fading=west]
  (0,-.1) -- (5,-.1) -- (5,-.2) -- (5.5,0) -- (5,.2) -- (5,.1) -- (0,.1) -- (0,-.1);
\end{tikzpicture}
\end{document}
```

**Comment by hanche** [comment] 2020-03-24 15:59
In that case, only the second arrow shows up. (To be certain, I changed the colour on the second one.)

**Comment by u-fischer** [comment] 2020-03-24 16:00
No don't change the color! The shadings must be identical.

**Comment by hanche** [comment] 2020-03-24 16:02
Only one showed up when they were identical, too.

**Comment by u-fischer** [comment] 2020-03-24 16:06
Yes, I just checked the numbers the shading resources have different names so this can't work. I need to think about it, there must be a way to get the resource in the page dictionary at least for test ;-)

**Comment by u-fischer** [comment] 2020-03-24 16:15
@hanche Well let's try this (I'm not sure about the number I copied them out of my pdf, but it could be that your pdf actually creates others):

```latex
\documentclass{article}
\usepackage{l3pdf}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff
\usepackage{tikz}
\usetikzlibrary{fadings,external}
\tikzexternalize[]
\begin{document}
\makeatletter \pgf@sys@addpdfresource@extgs@plain{%
 /pgfsmask28 <<
            /SMask <<
                 /S /Luminosity
                 /G 35 0 R
                  >>
             >>
 /pgfsmask35 <<
           /SMask <<
             /S /Luminosity
             /G 36 0 R
                 >>
             >>} 
\begin{tikzpicture}[scale=0.7]
  \fill[purple, path fading=west]
  (0,-.1) -- (5,-.1) -- (5,-.2) -- (5.5,0) -- (5,.2) -- (5,.1) -- (0,.1) -- (0,-.1);
\end{tikzpicture}
\end{document}
```

**Comment by hanche** [comment] 2020-03-24 16:17
That made a blank page.

**Comment by u-fischer** [comment] 2020-03-24 16:23
Can you sent me the pdf? Then I can check the numbers.

**Comment by hanche** [comment] 2020-03-24 16:30
Github won't let me upload it, so I need to find a different method to get it to you. (But I don't see the numbers you gave in there.) Let me just put it on my web site:

https://folk.ntnu.no/hanche/tmp/20200324.pdf

**Comment by hanche** [comment] 2020-03-24 17:20
Note to others: We moved this discussion to the TeX stackexchange chat. Not much useful information emerged, unfortunately.

**Comment by Mo-Gul** [comment] 2020-03-24 19:57
Maybe others want to follow too, you could paste the link to the chat here.

**Comment by hmenke** [comment] 2020-03-24 21:02
We also have a mailing list at pgf-tikz@tug.org where you can have extended discussions (sign up here https://tug.org/mailman/listinfo/pgf-tikz).

**Comment by hanche** [comment] 2020-03-25 06:55
Nothing much to see there (on the tex.se chat) really. Ulrike wanted to test some hypothesis, adding dictionaries to the pdf to see what happens. Since she does not have a Mac, I ran her code and checked the result. The hypothesis did not pan out, so that's the end of the story. But if you really are curious, start here:

https://chat.stackexchange.com/transcript/message/53887809#53887809

**Comment by hmenke** [comment] 2020-03-26 00:26
I'm pretty convinced by now that this an issue with Apple's PDF rendering engine.  So I'm closing this again.

**Closed as completed** 2020-03-26 00:27 UTC
Labels: closed-works-for-me, fadings, xetex, external, viewer-dependent
