### ISSUE TITLE
Using \tikzmath in 'node contents' does not work anymore (works in 3.0.1)

### ISSUE THREAD

**Issue by fshaked** [pgf-tikz/pgf#670] opened 2019-04-30 08:53 UTC
The minimal example below, which works with pgf 3.0.1, now fails with this error:
```
./test.tex:12: Undefined control sequence.
\tikz@math@if@@doifelse ->\pgfmathparse {\tikz@math@if@condition }\ifpgfmathfloatparseactive
                                                                                             \pgfmathfloattofixed {\pgfmathresult }\fi \let \tikz@math@if@falseaction =\tikz@math@collected \ifdim \pgfmathresult pt=0pt\relax \expandafter \tikz@math \exp...
l.12   }]
         ;
```

The example:
```
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{math}

\begin{document}
\begin{tikzpicture}
  \node[node contents={%
    \tikzmath{%
      if 0==0 then { print{0}; }%
      else { print{1}; };%
    }%
  }];
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment] 2019-04-30 10:44
Duplicate of https://github.com/pgf-tikz/pgf/issues/516

That was already fixed in f1c7cb0902f4e5bd5cf1ba63b954bd0371bed67b.

See also https://tex.stackexchange.com/questions/476038/cant-use-if-in-tikzmath-undefined-control-sequence-ifpgfmathfloatparseacti

Workaround:  Add `\usetikzlibrary{math}` to the preamble.

**Closed as completed by hmenke** 2019-04-30 10:44 UTC
Labels: closed-duplicate, tikzmath
