### ISSUE TITLE
Code example on p. 262 is not to the point

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#751] opened 2019-09-30 21:46 UTC
The code example under **Styles for pics.** on p. 262 is not really to the point, it describes how to use `every node` instead. You could replace it e.g. by

```
\begin{tikzpicture}[every pic/.style={scale=2,transform shape}] 
\pic foreach \x in {1,2,3} at (\x,0) {seagull};
\end{tikzpicture}
```

**Comment by hmenke** [comment] 2019-09-30 22:54
Exact duplicate of #519.
Please search existing issues before opening a new one.

**Closed as completed by hmenke** 2019-09-30 22:54 UTC
Labels: closed-duplicate
