### ISSUE TITLE
Tikz externalize - cannot find figures if numbering has changed

### ISSUE THREAD

**Issue by jeertmans** [pgf-tikz/pgf#1014] opened 2021-05-14 10:38 UTC
Hi everyone,
I am not sure it is a *bug* and rather a *feature* that I would like to be enhanced but here it is.

**Brief outline of the bug**
I am working with a lot of tikz pictures that I externalize using the Tikz externalize feature.
It works great but it seems that, when I try to insert or delete an image which is not at the end, Tikz will renumber each picture (seems logic) but will not guess that it has already generated the pictures, but with a different numbering.

I don't think it would really slow down the process to look, for every tikz picture, if its hash matches any of the already existing hashes -- or at least it would be nice to have the choice.

If I am mistaken, please do not hesitate to tell me !

**Minimal working example (MWE)**

```latex
\documentclass{article}

  % Any preamble code goes here

\usepackage{tikz}
\usepgfplotslibrary{external}
\tikzexternalize[prefix=figures/]

\begin{document}

\begin{tikzpicture}
% content of figure 0
\end{tikzpicture}

%%%%%%%% <---- Remove the picture right below and every subsequent 
%%%%%%%% ----- picture will be re-generated because their numbering has changed
\begin{tikzpicture}
% content of figure 1
\end{tikzpicture}
%%%%%%%%

%
% ...
%

\begin{tikzpicture}
% content of figure n-1
\end{tikzpicture}

\end{document}
```

**Comment by hmenke** [comment] 2021-05-14 11:46
Duplicate of https://github.com/pgf-tikz/pgf/issues/758

**Closed as completed** 2021-05-14 11:46 UTC
Labels: closed-duplicate, external
