### ISSUE TITLE
Throughout pgfmanual the "old syntax" for specifying circle radii is often used—such usages should be updated

### ISSUE THREAD

**Issue by cfraizer** [pgf-tikz/pgf#1306] opened 2024-01-14 08:17 UTC
### Version

3.1.10

### Details

Throughout the pgfmanual (TikZ & PGF Manual for Version 3.1.10), the "old syntax" for specifying circle paths (as described in the note in §14.6) is frequently used. As that syntax is no longer recommended—and because it is not explained until section §14.6 of the manual—perhaps we could update all (or most) of the instances to use the new (⟨coordinate⟩) circle [radius=⟨value⟩] syntax.

**Comment by hmenke** [comment] 2024-01-14 10:46
Duplicate of https://github.com/pgf-tikz/pgf/issues/999

**Closed as completed by hmenke** 2024-01-14 10:46 UTC
Labels: manual
