### ISSUE TITLE
ConText and PGF 3.1.3: undefined control sequence `\pgf@setup@shading@model`

### ISSUE THREAD

**Issue by jesseopdenbrouw** [pgf-tikz/pgf#697] opened 2019-06-24 08:31 UTC
Running ConText from TexLive 2019 (Windows 7) together with PGF 3.1.3 gives me this error: 

```
tex error       > tex error on line 577 in file D:/PRG/texlive/2019/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex: ! Undefined control sequence


\pgf@setup@shading@model ...delgrayfalse \XC@sdef
                                                  \pgf@mod@test {\XC@tgt@mod...
\pgfdeclareverticalshading ...setup@shading@model
                                                  \pgfutil@ifnextchar [\pgf@...
l.577 \pgfdeclareverticalshading
                              [tikz@axis@top,tikz@axis@middle,tikz@axis@bott...

567       \pgfutil@colorlet{tikz@axis@bottom}{#1}%
```
when running this simple TeX file:

```
\usemodule[tikz]

\starttext

\starttikzpicture
\draw (0,0) -- (2,0);
\stoptikzpicture

\stoptext
```

The line itself is drawn correctly.

**Comment by hmenke** [comment] 2019-06-24 08:43
Duplicate of https://github.com/pgf-tikz/pgf/issues/675
Please search existing issues first before opening a new one.

**Closed as completed by hmenke** 2019-06-24 08:43 UTC
Labels: closed-duplicate

**Comment by jesseopdenbrouw** [comment] 2019-06-24 09:11
Oops, sorry. For me, it didn't looked as the same problem.
